/* Generated By:JJTree: Do not edit this line. ASTCstNode.java */

package tools.extractor.ast;

public class ASTCstNode extends SimpleNode {
  double val;
  public ASTCstNode(int id) {
    super(id);
  }

  public ASTCstNode(EquationAST p, int id) {
    super(p, id);
  }

    public void setVal(double val) {
	this.val=val;
    }

  public String toString() { return (EquationASTTreeConstants.jjtNodeName[id]+" "+val); }

  public Double evaluate() throws ASTException {
    return(new Double(val));
  }

}
