/* Generated By:JJTree: Do not edit this line. ASTSimpleNode.java */

package tools.extractor.ast;

public class ASTSimpleNode extends SimpleNode {
  public ASTSimpleNode(int id) {
    super(id);
  }

  public ASTSimpleNode(EquationAST p, int id) {
    super(p, id);
  }

}
