/* Generated By:JJTree: Do not edit this line. EquationASTTreeConstants.java */

package tools.extractor.ast;

public interface EquationASTTreeConstants
{
  public int JJTVOID = 0;
  public int JJTADDNODE = 1;
  public int JJTSUBTRACTNODE = 2;
  public int JJTMULNODE = 3;
  public int JJTDIVNODE = 4;
  public int JJTID = 5;
  public int JJTCSTNODE = 6;


  public String[] jjtNodeName = {
    "void",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "Id",
    "CstNode",
  };
}
