/* Generated By:JJTree&JavaCC: Do not edit this line. EquationASTConstants.java */
package tools.extractor.ast;

public interface EquationASTConstants {

  int EOF = 0;
  int INT = 6;
  int INTEGER_LITERAL = 7;
  int IDENTIFIER = 14;
  int LETTER = 15;
  int DIGIT = 16;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"int\"",
    "<INTEGER_LITERAL>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
